#!/usr/bin/env bash

set -e

if ! [[ "$1" =~ ^(web|api)$ ]]; then
  echo "Please provide a valid package name. valid options: api, web" >&2
  exit 1
fi

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_COMMIT_SHA=${GITHUB_SHA:-$(git rev-parse HEAD)}

deploy () {
  # VERCEL_TOKEN
  token="VpcyGrjb0uOvrXsxGiyhxWIe"
  # VEREL_ORG_ID
  orgId="s0u8XySVq3EH7yrs1IRNb3Hj"
  # VERCEL_PROJECT_ID
  projectId=""
  # Initial vercel cli args
  args=(
    "-t ${token} -c -C"
    "-m githubCommitSha=${GIT_COMMIT_SHA}"
    "-m githubDeployment=1"
    "-m githubOrg=${GITHUB_ORG_NAME}"
    "-m githubCommitOrg=${GITHUB_ORG_NAME}"
    "-m githubRepo=${GITHUB_REPO}"
    "-m githubCommitRepo=${GITHUB_REPO}"
    "-m githubCommitRef=${GIT_BRANCH}"
    "-m githubCommitMessage=${GIT_COMMIT_MSG}"
    "-m githubCommitAuthorLogin: ${COMMIT_AUTHOR}"
    "-m githubCommitAuthorName: ${COMMIT_AUTHOR_NAME}"
  )

  # githubCommitAuthorLogin: "dependabot[bot]"
  # githubCommitAuthorName: "dependabot[bot]"
  # githubCommitMessage: "chore(deps): bump next from 8.1.0 to 9.3.3↵↵Bumps [next](https://github.com/zeit/next.js) from 8.1.0 to 9.3.3.↵- [Release notes](https://github.com/zeit/next.js/releases)↵- [Commits](https://github.com/zeit/next.js/compare/v8.1.0...v9.3.3)↵↵Signed-off-by: dependabot[bot] <support@github.com>"
  # githubCommitOrg: "mediaupstream"
  # githubCommitRef: "dependabot/npm_and_yarn/next-9.3.3"
  # githubCommitRepo: "dead-drop-io"
  # githubCommitSha: "e1814bed459297394a4c78a6fbf888f027dfbab6"
  # githubDeployment: "1"
  # githubOrg: "mediaupstream"
  # githubRepo: "dead-drop-io"

  if [ -n "$COMMIT_AUTHOR" ]; then
    args+=(
      "-m githubCommitAuthorName=\"${COMMIT_AUTHOR}\""
      "-m githubCommitAuthorLogin=\"${COMMIT_AUTHOR}\""
    )
  fi

  # deploying api?
  if [ $1 = "api" ]; then
    projectId="prj_LQmlubkLgUq9jNtGmAiS6Qp0Llyv"
  fi

  # deploying web?
  if [ $1 = "web" ]; then
    projectId="prj_1ov6CWEJ2FOEAdMmJAvrk4QQjHWx"
    # set API_URL as build/env vars for the vercel cli
    if [ -n "$API_URL" ]; then
      args+=(
        "-b API_URL=${API_URL}"
        "-e API_URL=${API_URL}"
      )
    else
      echo "Please provide API_URL" >&2
      return 1
    fi
  fi

  # production deploy?
  if [ -n "$PROD_RELEASE" ]; then
    args+=("--prod")
  fi

  echo ${args[@]} >&2

  deployment=$( \
    VERCEL_ORG_ID=${orgId} \
    VERCEL_PROJECT_ID=${projectId} \
    npx vercel ${args[@]})

  # return the deployment URL
  echo "$deployment"
}

echo $(deploy $1)
